id: ID73DABB1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T00:04:38+00:00'
last_modified: '2022-06-15T18:22:19.220983+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24862
  title: དམངས་ཁྲོད་རྩོམ་རིག་རྣམ་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    BB31:
      image_group_id: I1KG24864
      title: Volume 1 of dmangs khrod rtsom rig rnam bshad/
      total_pages: 328
      order: 1
      base_file: BB31.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
